### ISSUE TITLE
引用工程后app崩溃

### ISSUE THREAD

**Issue by 1196278096** [MeetYouDevs/Android-Skin#7]
java.lang.NoSuchMethodError: android.support.v4.view.LayoutInflaterCompat.setFactory2
                                                       at com.meiyou.skinlib.AndroidSkinHook.hookLayoutInflater(AndroidSkinHook.java:73)
                                                       at com.meiyou.skinlib.AndroidSkinHook.access$100(AndroidSkinHook.java:17)
                                                       at com.meiyou.skinlib.AndroidSkinHook$1.onActivityCreated(AndroidSkinHook.java:32)
                                                       at android.app.Application.dispatchActivityCreated(Application.java:218)
                                                       at android.app.Activity.onCreate(Activity.java:917)
                                                       at com.example.module.IndexActivity.onCreate(IndexActivity.java:115)
                                                       at android.app.Activity.performCreate(Activity.java:5286)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2233)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1232)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by 1196278096** [comment]
sdk更新到26后 support包只有26.0.0-alpha1，然后按简介使用 app还是会崩溃，去掉换肤功能代码运行正常。错误日志：
12-18 13:58:28.023 1681-1681/com.example.shapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.dhzwan.shapp, PID: 1681
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.shapp/com.dhzwan.example.module.main.MainActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class TextView
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:135)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1232)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class TextView
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                                    at android.app.Activity.setContentView(Activity.java:1949)
                                                                    at com.example.shapp.module.main.MainActivity.onCreate(MainActivity.java:81)
                                                                    at android.app.Activity.performCreate(Activity.java:5286)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2233)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319) 
                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:135) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1232) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5253) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x0
                                                                    at android.content.res.Resources.getResourceEntryName(Resources.java:1878)
                                                                    at com.meiyou.skinlib.attr.MutableAttrFactory.create(MutableAttrFactory.java:25)
                                                                    at com.meiyou.skinlib.AndroidAttrManager.obtainMutableAttrList(AndroidAttrManager.java:71)
                                                                    at com.meiyou.skinlib.AndroidSkinFactory.saveAttrs(AndroidSkinFactory.java:98)
                                                                    at com.meiyou.skinlib.AndroidSkinFactory.onCreateView(AndroidSkinFactory.java:74)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                    at android.app.Activity.setContentView(Activity.java:1949) 
                                                                    at com.dhzwan.shapp.module.main.MainActivity.onCreate(MainActivity.java:81) 
                                                                    at android.app.Activity.performCreate(Activity.java:5286) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2233) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319) 
                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:135) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1232) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5253) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by iceAnson** [comment]
请贴一下布局文件

**Comment by 1196278096** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/main_root_lyt"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    
    <FrameLayout
        android:id="@+id/main_title_lyt"
        android:layout_width="match_parent"
        android:layout_height="44dp"
        android:background="@drawable/title_bg" >

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="left|center_vertical"
            android:layout_marginLeft="6dp"
            android:src="@drawable/title_user_img"/>

        <TextView
            android:id="@+id/title_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:gravity="center_vertical"
            android:text="@string/app_name"
            android:textColor="@color/common_title_color"
            android:textSize="@dimen/common_title_size" />

        <ImageView
            android:id="@+id/title_menu_image_home"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:padding="10dp"
            android:layout_marginRight="2dp"
            android:layout_gravity="right|center_vertical"
            android:scaleType="centerInside"
            android:clickable="true"
            android:src="@drawable/btn_title_add"
            android:visibility="visible" />

        <ImageView
            android:id="@+id/title_menu_image_info"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="10dp"
            android:layout_marginRight="2dp"
            android:layout_gravity="right|center_vertical"
            android:scaleType="centerInside"
            android:clickable="true"
            android:src="@drawable/btn_title_more"
            android:visibility="gone" />

    </FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:background="@color/common_space_line_title"/>
    
    <FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:padding="0dp"
        android:background="@drawable/activity_bg">
    </FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:background="@color/common_space_line_bottom_menu"/>

    <LinearLayout android:id="@+id/bottom_menu_lyt"
        android:layout_width="match_parent"
        android:layout_height="49dp"
        android:background="@drawable/bottom_menu_bg"
        android:gravity="center_vertical" >

        <LinearLayout
            android:id="@+id/home_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:layout_weight="1" 
            android:gravity="center">

 

                <ImageView
                    android:id="@+id/home_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_home_selected" />

                <TextView
                    android:id="@+id/home_text"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:paddingTop="2dp"
                    android:text="@string/home"
                    android:textSize="@dimen/main_bottom_menu_size"
                    android:textColor="@color/bottom_menu_text_selected" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/info_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1" 
            android:orientation="vertical"
            android:gravity="center">

            <FrameLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_gravity="center">

                <ImageView
                    android:id="@+id/info_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="5dp"
                    android:layout_marginRight="5dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_info_nor" />

                <View
                    android:id="@+id/newinfo_flag"
                    android:layout_width="8dp"
                    android:layout_height="8dp"
                    android:layout_gravity="top|right"
                    android:gravity="center"
                    android:background="@drawable/flag_circle_shape"
                    android:visibility="gone" />

            </FrameLayout>

            <TextView
                android:id="@+id/info_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                android:text="@string/info"
                android:textSize="@dimen/main_bottom_menu_size"
                android:textColor="@color/bottom_menu_text_nor" />


        </LinearLayout>

        <LinearLayout
            android:id="@+id/service_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:orientation="vertical"
            android:gravity="center" >

            
                
                
                
                
                
                <ImageView
                    android:id="@+id/service_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_service_nor" />
            













            
            
            <TextView
                 android:id="@+id/service_text"
                 android:layout_width="wrap_content"
                 android:layout_height="wrap_content"
                 android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                 android:text="@string/service"
                 android:textSize="@dimen/main_bottom_menu_size"
                 android:textColor="@color/bottom_menu_text_nor" />
            
        </LinearLayout>

        <LinearLayout
            android:id="@+id/more_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1" 
            android:orientation="vertical"
            android:gravity="center">

            <FrameLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_gravity="center" >

                <ImageView
                    android:id="@+id/more_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_more_nor" />

                

                <TextView
                    android:id="@+id/user_info_flag"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="right|top"
                    android:gravity="center"
                    android:text="1"
                    android:textSize="10dp"
                    android:textColor="#ffffff"
                    android:textStyle="bold"
                    android:background="@drawable/unread_bg"
                    android:visibility="gone"/>

            </FrameLayout>

            <TextView
                android:id="@+id/more_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                android:text="@string/more"
                android:textSize="@dimen/main_bottom_menu_size"
                android:textColor="@color/bottom_menu_text_nor" />
        </LinearLayout>
    </LinearLayout>

</LinearLayout>

**Comment by 1196278096** [comment]
贴的时候是正常的 保存了后布局文件好像少了一部分，顶部是
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/main_root_lyt"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

**Comment by iceAnson** [comment]
能否贴个完整的附件

**Comment by 1196278096** [comment]
代码是公司项目中的 不能全发出来。这布局文件我是全部粘贴了 但是显示的时候就没有了

**Comment by iceAnson** [comment]
从错误日志上看，是某个TextView加载的时候错误了，你把那个TextView的布局贴出来即可，我用demo调试

**Comment by 1196278096** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/main_root_lyt"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    
    <FrameLayout
        android:id="@+id/main_title_lyt"
        android:layout_width="match_parent"
        android:layout_height="44dp"
        android:background="@drawable/title_bg" >

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="left|center_vertical"
            android:layout_marginLeft="6dp"
            android:src="@drawable/title_user_img"/>

        <TextView
            android:id="@+id/title_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:gravity="center_vertical"
            android:text="@string/app_name"
            android:textColor="@color/common_title_color"
            android:textSize="@dimen/common_title_size" />

        <ImageView
            android:id="@+id/title_menu_image_home"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:padding="10dp"
            android:layout_marginRight="2dp"
            android:layout_gravity="right|center_vertical"
            android:scaleType="centerInside"
            android:clickable="true"
            android:src="@drawable/btn_title_add"
            android:visibility="visible" />

        <ImageView
            android:id="@+id/title_menu_image_info"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="10dp"
            android:layout_marginRight="2dp"
            android:layout_gravity="right|center_vertical"
            android:scaleType="centerInside"
            android:clickable="true"
            android:src="@drawable/btn_title_more"
            android:visibility="gone" />

    </FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:background="@color/common_space_line_title"/>
    
    <FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:padding="0dp"
        android:background="@drawable/activity_bg">
    </FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:background="@color/common_space_line_bottom_menu"/>

    <LinearLayout android:id="@+id/bottom_menu_lyt"
        android:layout_width="match_parent"
        android:layout_height="49dp"
        android:background="@drawable/bottom_menu_bg"
        android:gravity="center_vertical" >

        <LinearLayout
            android:id="@+id/home_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:layout_weight="1" 
            android:gravity="center">

 

                <ImageView
                    android:id="@+id/home_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_home_selected" />

                <TextView
                    android:id="@+id/home_text"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:paddingTop="2dp"
                    android:text="@string/home"
                    android:textSize="@dimen/main_bottom_menu_size"
                    android:textColor="@color/bottom_menu_text_selected" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/info_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1" 
            android:orientation="vertical"
            android:gravity="center">

            <FrameLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_gravity="center">

                <ImageView
                    android:id="@+id/info_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="5dp"
                    android:layout_marginRight="5dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_info_nor" />

                <View
                    android:id="@+id/newinfo_flag"
                    android:layout_width="8dp"
                    android:layout_height="8dp"
                    android:layout_gravity="top|right"
                    android:gravity="center"
                    android:background="@drawable/flag_circle_shape"
                    android:visibility="gone" />

            </FrameLayout>

            <TextView
                android:id="@+id/info_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                android:text="@string/info"
                android:textSize="@dimen/main_bottom_menu_size"
                android:textColor="@color/bottom_menu_text_nor" />


        </LinearLayout>

        <LinearLayout
            android:id="@+id/service_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:orientation="vertical"
            android:gravity="center" >

            
                
                
                
                
                
                <ImageView
                    android:id="@+id/service_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_service_nor" />
            













            
            
            <TextView
                 android:id="@+id/service_text"
                 android:layout_width="wrap_content"
                 android:layout_height="wrap_content"
                 android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                 android:text="@string/service"
                 android:textSize="@dimen/main_bottom_menu_size"
                 android:textColor="@color/bottom_menu_text_nor" />
            
        </LinearLayout>

        <LinearLayout
            android:id="@+id/more_menu_layout"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1" 
            android:orientation="vertical"
            android:gravity="center">

            <FrameLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_gravity="center" >

                <ImageView
                    android:id="@+id/more_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/menu_b_more_nor" />

                

                <TextView
                    android:id="@+id/user_info_flag"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="right|top"
                    android:gravity="center"
                    android:text="1"
                    android:textSize="10dp"
                    android:textColor="#ffffff"
                    android:textStyle="bold"
                    android:background="@drawable/unread_bg"
                    android:visibility="gone"/>

            </FrameLayout>

            <TextView
                android:id="@+id/more_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingTop="2dp"
                android:text="@string/more"
                android:textSize="@dimen/main_bottom_menu_size"
                android:textColor="@color/bottom_menu_text_nor" />
        </LinearLayout>
    </LinearLayout>

</LinearLayout>

**Comment by iceAnson** [comment]
common_title_color这个发一下

**Comment by 1196278096** [comment]
<color name="common_title_color">#fff</color>

**Comment by iceAnson** [comment]
奇怪，没测出问题，你能不能fork一下，然后把测试代码提交一下？然后地址发我，我clone下来看看

**Comment by 1196278096** [comment]
你的demo我导入后使用compile 'com.meiyou:android-skin:1.0.7'能跑起来的，但是用compile project(':skinlib')跑不起来。是不是资源文件必须用引用，像字体色值不能直接字符#ffffff格式？

**Comment by 1196278096** [comment]
确实是布局文件中不能使用android:textColor="#ffffff"格式，改成引用就好了

**Comment by iceAnson** [comment]
好的，我fix一下

**Comment by iceAnson** [comment]
fix了，请升级1.0.8
